title: Diogo Ramalho
description: [Linkedin] (https://www.linkedin.com/in/dramalhoeng)
show_download: true
theme: jekyll-theme-minimal

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: Portfolio
  description: ML Portfolio Projects
  url: https://github.com/diogormec/Portfolio
